# Generated by Django 4.1 on 2022-10-14 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_control', '0004_alter_player_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_state', models.CharField(choices=[('W', 'Writing'), ('A', 'Answering')], max_length=1)),
                ('host', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_control.player')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('correct_answer', models.CharField(max_length=100)),
                ('ans_1', models.CharField(max_length=100)),
                ('ans_2', models.CharField(max_length=100)),
                ('ans_3', models.CharField(max_length=100)),
                ('ans_4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_state', models.CharField(max_length=100)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game_api.game')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game_api.question')),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_state', models.CharField(choices=[('R', 'Ready'), ('W', 'Waiting'), ('A', 'Answering')], max_length=1)),
                ('points', models.IntegerField(blank=True, default=0, null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game_api.game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_control.player')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_state', models.CharField(choices=[('R', 'Ready'), ('W', 'Waiting'), ('A', 'Answering')], max_length=1)),
                ('player_answer', models.CharField(max_length=100)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_control.player')),
                ('round', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game_api.round')),
            ],
        ),
    ]
