# Generated by Django 4.1 on 2022-10-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0002_alter_game_game_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lobby',
            name='acepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='round',
            name='round_state',
            field=models.CharField(choices=[('W', 'Writing'), ('A', 'Answering'), ('S', 'Starting')], max_length=1),
        ),
    ]
