# Generated by Django 4.1 on 2022-10-15 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0004_alter_player_user'),
        ('game_api', '0004_rename_acepted_lobby_acepted_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_control.player'),
        ),
    ]
