# Generated by Django 4.1 on 2022-09-28 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_won', models.IntegerField()),
                ('matches_lost', models.IntegerField()),
                ('best_score', models.IntegerField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('acepted_request', models.BooleanField()),
                ('reciever_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciever_player', to='user_control.player')),
                ('sender_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_player', to='user_control.player')),
            ],
        ),
    ]
