# Generated by Django 4.1 on 2022-09-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequests',
            name='name',
        ),
        migrations.AlterField(
            model_name='player',
            name='best_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='matches_lost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='matches_won',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
