# Generated by Django 4.1 on 2022-10-24 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0006_alter_player_best_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='best_answer',
            field=models.CharField(blank=True, default='No best answer yet', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='creation_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='group_playing',
            field=models.CharField(blank=True, default='Yo literalmente no sé jugar', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='many_friends',
            field=models.CharField(blank=True, default='No tengo amigos', max_length=100, null=True),
        ),
    ]
