# Generated by Django 4.1 on 2022-10-24 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0007_alter_player_best_answer_alter_player_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='best_answer',
        ),
        migrations.RemoveField(
            model_name='player',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='player',
            name='current_date',
        ),
        migrations.RemoveField(
            model_name='player',
            name='friends_amount',
        ),
        migrations.RemoveField(
            model_name='player',
            name='group_playing',
        ),
        migrations.RemoveField(
            model_name='player',
            name='invites_made',
        ),
        migrations.RemoveField(
            model_name='player',
            name='many_friends',
        ),
        migrations.RemoveField(
            model_name='player',
            name='match_percentage',
        ),
        migrations.RemoveField(
            model_name='player',
            name='played_rounds',
        ),
        migrations.RemoveField(
            model_name='player',
            name='round_percentage',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_matches',
        ),
        migrations.RemoveField(
            model_name='player',
            name='won_rounds',
        ),
    ]
