# Generated by Django 4.1 on 2022-10-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0008_remove_player_best_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='best_score',
        ),
        migrations.RemoveField(
            model_name='player',
            name='matches_lost',
        ),
        migrations.RemoveField(
            model_name='player',
            name='matches_won',
        ),
    ]
