# Generated by Django 4.1 on 2022-10-24 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0009_remove_player_best_score_remove_player_matches_lost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='best_answer',
            field=models.CharField(blank=True, default='No best answer yet', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='best_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='creation_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='current_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='friends_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='group_playing',
            field=models.CharField(blank=True, default='Yo literalmente no sé jugar', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='invites_made',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='many_friends',
            field=models.CharField(blank=True, default='No tengo amigos', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='match_percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='matches_lost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='matches_won',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='played_rounds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='round_percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='total_matches',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='won_rounds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
